# Generated by Django 5.2.10 on 2026-03-02 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resumeanalysis_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_job', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('roadmap_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
