# Generated by Django 5.2.10 on 2026-03-04 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_timelineroadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineroadmap',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timelineroadmap',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_roadmap', to=settings.AUTH_USER_MODEL),
        ),
    ]
