# Generated by Django 5.2.10 on 2026-01-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
